[webservers]
web-1 ansible_host= fqdn=fhmiv1pbp0kvlc1lkp6p.auto.internal
web-2 ansible_host= fqdn=fhm7as3g5a6jpa27okgo.auto.internal

[databases]
main ansible_host=111.88.243.66 fqdn=fhmn7ghulo625ok0jm1k.auto.internal
replica ansible_host=111.88.241.170 fqdn=fhmdvs2ai6514ec2vmj0.auto.internal

[storage]
storage ansible_host=111.88.241.188 fqdn=fhmkuuo4lmute32al32i.auto.internal
