#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - ca-certificates
  - software-properties-common
  - gnupg-agent

# задание пользователя

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}

runcmd:
  # Установка Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io

  # Добавление пользователя ubuntu в группу docker
  - sudo usermod -aG docker ubuntu

  # Установка Docker Compose
  - sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

  # Создание символической ссылки для совместимости
  - sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose

  # Включение и запуск Docker
  - sudo systemctl enable docker
  - sudo systemctl start docker

  # Проверка установки
  - docker --version
  - docker-compose --version

final_message: "Установка докер завершена"
